# Generated by Django 2.2 on 2019-12-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='billing_address',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='billing_city',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='billing_zip',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='shipping_address',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='shipping_city',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='shipping_zip',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='shoe_size',
            field=models.FloatField(default='', null=True),
        ),
    ]
