# Generated by Django 3.0 on 2019-12-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='back_img',
            field=models.ImageField(default=None, upload_to='uploads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='bottom_img',
            field=models.ImageField(default=None, upload_to='uploads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='front_img',
            field=models.ImageField(default=None, upload_to='uploads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='left_img',
            field=models.ImageField(default=None, upload_to='uploads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='right_img',
            field=models.ImageField(default=None, upload_to='uploads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='top_img',
            field=models.ImageField(default=None, upload_to='uploads'),
            preserve_default=False,
        ),
    ]
