# Generated by Django 2.2 on 2019-12-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_app', '0002_auto_20191218_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='item_sex',
            new_name='item_gender',
        ),
    ]
