# Generated by Django 2.2 on 2019-12-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_app', '0003_auto_20191218_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='shoe_size',
            field=models.FloatField(null=True),
        ),
    ]
