# Generated by Django 2.2 on 2019-12-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_app', '0004_auto_20191218_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='billing_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='billing_city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='billing_zip',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='shipping_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='shipping_city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='shipping_zip',
            field=models.IntegerField(null=True),
        ),
    ]
